from rep import apply
P = "/Users/wanjun/Desktop/gptr/dev/spec/04-interface-contract.md"
pairs = [
("""| `preset_tools(preset, human, model = NULL, modifiers = character())` | `prompt-sections.R` | chr of direct tool names: `minimal` = `read`, `r`, `edit`, `write`; `standard` = minimal + `ask` when `human`; `readonly` = `read`, `r` (+ `ask`); `extended` = standard + `grep`, `find`, `ls`; then `+name`/`-name` modifiers and per-model `tools.presets` settings | P06, P11, P19 |""",
"""| `preset_tools(preset, human, model = NULL, modifiers = character(), mode = NULL)` | `prompt-sections.R` | chr of direct tool names from the registered `preset` record (IC-69): `minimal` = `read`, `r`, `edit`, `write`; `standard` = minimal + `ask` when `human`, or when `mode` is `manual` without a human (NS-12, IC-68); `readonly` = `read`, `r` (+ `ask`); `extended` = standard + `grep`, `find`, `ls`; then `+name`/`-name` modifiers and per-model `tools.presets` settings (shipped defaults for Gemini 3 and Haiku 4.5, IC-73); any spec with an `execute` may be named (IC-37) | P07, P11 (P06 and P19 only through `prompt.freeze`, IC-34) |
| `session_add_tools(s, specs)` (service `session.add_tools`) | `prompt-sections.R` | registers `specs` at rank 0 for `s`; an operator `tool_change` message with their declarations when the adapter declares `tool_addition`, else they become `r` members announced in an operator note; the frozen array never changes (IC-69) | P06 (`ctx$add_tools()`), P08 (continuations with `tools =`, `plugins =`, `extensions =`) |"""),
("""| `context_first_message(s, input)` | `prompt-context.R` | the blocks of the first user message in the §7.4 order of `03`: every `context_block` spec with `placement = "first"` in `order`,""",
"""| `context_first_message(s, input)` | `prompt-context.R` | the blocks of the first user message in the §7.4 order of `03`: every `context_block` spec with `placement = "first"` or `"both"` in `order` (so `<attached>` is in the first message, IC-38),"""),
("""| `context_turn_blocks(s, input)` | `prompt-context.R` | the leading blocks of a later user message (`placement = "turn"` specs: `workspace_changes`, `attached`, mode changes, skill activations); only non-empty blocks | P06 (through the §7.0 services) |""",
"""| `context_turn_blocks(s, input)` | `prompt-context.R` | the leading blocks of a later user message (`placement = "turn"` or `"both"` specs: `workspace_changes`, `attached`, mode changes, skill activations); only non-empty blocks; a block whose text hash equals the last one emitted under the same name in this session is skipped (IC-38) | P06 (through the §7.0 services) |"""),
("""| `builtin_prompt(gptr)`, `builtin_context(gptr)`, `builtin_compaction(gptr)` | | register sections, the gap `cache_policy`, the default `estimator`, the context blocks `project_instructions`, `environment`, `mode`, `plan`, and the checkpoint `compactor` | P02 load |""",
"""| `builtin_prompt(gptr)`, `builtin_context(gptr)`, `builtin_compaction(gptr)` | | register P07's sections (`preamble`, `tools`, the closing lines of `rules`, the core of `r_session`, `r_performance`, `modes`, `context`, `addendum`; IC-68), the four `preset` records, the gap `cache_policy`, the default `estimator`, the context blocks `project_instructions` (rendered `trusted="false"` in an untrusted project, IC-52), `environment`, `mode`, `plan`, and the checkpoint `compactor` (with the post-compaction floor check, IC-71) | P02 load |"""),
("""| `gateway_run(call, s = NULL)` | the default System 2 runner used by the `continue`/`new` routes and by other routes: creates the session when `s` is `NULL` (`session_new()` with the resolved model, mode and home), applies model/mode changes,""",
"""| `gateway_run(call, s = NULL)` | the default System 2 runner used by the `continue`/`new` routes and by other routes: creates the session when `s` is `NULL` (`session_new()` with the resolved model, mode and home; a router model is stored as `router:<name>`, IC-69), chooses the evaluation environment by the IC-40 precedence and checks that context symbols are visible there, applies model/mode changes and `session_add_tools()` for `tools =`/`plugins =`/`extensions =` on a continuation, tightens the mode to the running one when `run_current()` is non-NULL (IC-53),"""),
("""| `trust_get(path = getwd())` | `lgl(1)`: `TRUE` only when recorded | P03, P07, P15, P17, P18 |""",
"""| `trust_get(path = getwd())` | `lgl(1)`: `TRUE` only when recorded and the trust fingerprint still matches (IC-52); L0 and L3 callers use the `trust.get` service (IC-33) | P08; P03, P07, P15, P17, P18 through `trust.get` |"""),
("""| `replay_mode(arg = NULL)` | `chr(1)`: `arg` > `gptr.replay` > `GPTR_REPLAY` > settings > `"auto"`; `"replay"` is forced when `check_running()` or in a vignette build | P08, P13, P15, P19 |
| `replay_guard(model, what = "model call")` | in replay mode, signals `gptr_error_not_recorded` before any request to a provider whose record is not `offline = TRUE` (the fake provider is offline, so tests and examples still run); `invisible(TRUE)` otherwise | P08 (`gateway_run()`), P13 (cache misses), P19 (team and fan-out children) |
| `egress_check(provider_id)` | `invisible(TRUE)` if acknowledged (user settings `egress`), local or offline, or `.opts$context = "none"`; with a human: shows what automatic context is sent and records the acknowledgement at user scope; otherwise `gptr_error_egress` | P08 (`gateway_run()`), P13, P19 |""",
"""| `replay_mode(arg = NULL)` | `chr(1)`: `arg` > `gptr.replay` > `GPTR_REPLAY` > settings > `"auto"`; `"replay"` is forced when `check_running()` and `Sys.getenv("TESTTHAT") != "true"` (examples), unless `arg` is given (IC-45) | P08, P13, P15, P19 |
| `replay_guard(model, what = "model call")` | in replay mode, signals `gptr_error_not_recorded` before any request to a provider whose record is not `offline = TRUE` (`offline` = no remote model is called: the fake provider and the mock-server and fake-CLI test providers, so tests and examples still run); `invisible(TRUE)` otherwise | P08 (`gateway_run()`), P13 (cache misses), P19 (team and fan-out children) |
| `egress_check(provider_id)` | `invisible(TRUE)` if acknowledged (user settings `egress`), local or offline, or `.opts$context = "none"`; when `gptr_can_prompt()`: shows what automatic context is sent and records the acknowledgement at user scope (an `ask_human`, IC-53); otherwise `gptr_error_egress` | P08 (`gateway_run()`), P13, P19 |"""),
("""| `eval_r(code, envir, timeout = NULL, plots = c("auto", "capture", "none"), tee = gptr_has_human(), budget_tokens = gptr_opt("r_output_tokens"), guard = TRUE, rng = NULL, record = TRUE)` | `eval-core.R` | parses with `srcfilecopy("<gptr>", code)`; `eval_guard()`; evaluates top-level expressions one by one in `envir` with sink capture (cleaned up in `suspendInterrupts()`), calling handlers created in a frame that does not hold `envir` [R2][R3], per-expression `setTimeLimit(elapsed = timeout, transient = TRUE)` (`timeout = NULL`: none with a human present, else `gptr.r_timeout`), symbols printed with `print(<sym>)` in `envir` [R8], plots captured and replayed to PNG, interruptions recorded with `on.exit()`, `rng` (an L'Ecuyer seed) swapped in and out around the evaluation; stops at the first error; returns a `gptr_eval_result` (§5.8); never keeps the value | P10 (`r`), P14 (`!expr`), P18 (server `r`) |""",
"""| `eval_r(code, envir, timeout = NULL, plots = c("auto", "capture", "none"), tee = gptr_has_human(), budget_tokens = gptr_opt("r_output_tokens"), guard = TRUE, rng = NULL, record = TRUE, max_images = gptr_opt("r_max_images"))` | `eval-core.R` | the built-in `evaluator` record `r` (IC-69); parses with `srcfilecopy("<gptr>", code)`; `eval_guard()`; evaluates top-level expressions one by one in `envir` with sink capture (cleaned up in `suspendInterrupts()`), calling handlers created in a frame that does not hold `envir` [R2][R3], per-expression `setTimeLimit(elapsed = timeout, transient = TRUE)` (`timeout = NULL`: none with a human present, else `gptr.r_timeout`), symbols printed with `print(<sym>)` in `envir` and every `withVisible()` result cleared in place (`res[1L] = list(NULL)`) before the frame returns [R8, IC-67], plots captured (on `pdf(NULL)` with the display list enabled when no device is open and no human sees one; the prior device restored) and replayed to PNG, at most `max_images` attached (the rest kept in the session's out store), interruptions recorded with `on.exit()`, the agent's L'Ecuyer state swapped in and out by `rng_swap()` (IC-61); stops at the first error; returns a `gptr_eval_result` (§5.8); never keeps the value | P10 (`r`), P14 (`!expr`), P18 (server `r`) |
| `rng_swap(state, expr)` [leaf] | `eval-core.R` | saves `.Random.seed` of the global environment (or its absence), assigns the agent's `c(10407L, <6 seeds>)`, evaluates, stores the advanced vector back in `state`, restores or removes the user's; with `with_seed_preserved()` the only code that assigns `.Random.seed` (IC-61) | P09, P19 |"""),
("""| `eval_guard(exprs)` | `eval-guard.R` | `list(blocked = chr, reason = chr(1) \\| NULL)` for `q`, `quit`, `readline`, `menu`, `browser`, ... [12 §3.6]; a literal `[secret:` marker is blocked with the `Sys.getenv()` hint | P09, P18 |""",
"""| `eval_guard(exprs)` | `eval-guard.R` | `list(blocked = chr, reason = chr(1) \\| NULL)` for `q`, `quit`, `readline`, `menu`, `browser`, ... [12 §3.6]; the symbols `q` and `quit` are flagged in any position (a value, a `FUN` argument, `match.fun`, `get`, `do.call`, `base::`; IC-67); a literal `[secret:` marker is blocked with the `Sys.getenv()` hint | P09, P18 |"""),
("""| `builtin_workspace(gptr)` | `env-snapshot.R` | registers context blocks `workspace` (`first`, order 500), `workspace_changes` (`turn`, order 100), `attached` (`turn`, order 600) and the prompt section `r_env` (T1, order 900) | P02 load |""",
"""| `builtin_workspace(gptr)` | `env-snapshot.R` | registers context blocks `workspace` (`first`, order 500), `workspace_changes` (`turn`, order 100), `attached` (`both`, order 600), `skill_content` preloads (`both`, order 700) (IC-38), the prompt section `r_env` (T1, order 900), the `evaluator` record `r` and the `describe` and `eval.r` services | P02 load |"""),
("""| `ns_resolve(path)` (service `ns.resolve`) | `tool-namespace.R` | resolves `gptr$<a>` / `gptr$<a>$<b>...` to a member closure or a `gptr_ns` node from `r`-exposure tool specs and namespace providers (MCP: P18 calls `ns_register_provider("mcp", ...)`); no I/O | P08 |""",
"""| `ns_resolve(path)` (service `ns.resolve`), `ns_names(pattern)` (service `ns.names`) | `tool-namespace.R` | resolves `gptr$<a>` / `gptr$<a>$<b>...` to a member closure or a `gptr_ns` node from un-namespaced tool specs with a `fun` that are not `hidden` (IC-37) and namespace providers (MCP: P18 calls `ns_register_provider("mcp", ...)`); lists names for completion; no I/O | P08 (the gateway methods) |"""),
("""| `builtin_tools(gptr)`, `builtin_r(gptr)` | `tool-namespace.R`, `tool-r.R` | register the direct tools `read`, `edit`, `write` (+ `grep`, `find`, `ls` for the extended preset), `r`, and the members of §9.4 | P02 load |""",
"""| `builtin_tools(gptr)`, `builtin_r(gptr)` | `tool-namespace.R`, `tool-r.R` | register one spec per capability with both `execute` and `fun` for `read`, `edit`, `write`, `grep`, `find`, `ls` (IC-37), the `r` tool (its `parameters` a function of `ctx` giving the four schema variants, IC-68), the other members of §9.4 owned by P10 (including `out`, IC-36), their `guidelines` for `<rules>`, the `r_session` fragments for helpers and `out`, the `plugins` section, the `search_source` record for members, and the services `ns.resolve`, `ns.names`, `search.sources` | P02 load |"""),
("""| `builtin_ui(gptr)` | `console-ui.R` | registers `ui` specs `console`, `none`, `scripted`, `rstudio` and the `ui.get` service (resolution: `options(gptr.ui)`, else `console` when `gptr_has_human()` or IRkernel, else `none`) | P02 load |""",
"""| `builtin_ui(gptr)` | `console-ui.R` | registers `ui` specs `console`, `none`, `scripted`, `rstudio` and the `ui.get` service (resolution from the run's snapshot of `gptr.ui`, else `console` when `gptr_can_prompt()`, else `none`, IC-43, IC-53); every display escapes control, bidi and zero-width characters and the one-line prompt lists every flagged call and `+N more lines` (IC-53) | P02 load |"""),
("""`checkpoint.note` service), session = chr(1), turn = int(1), nested = lgl(1))`.""",
"""`checkpoint.note` service), session = chr(1), turn = int(1), nested = lgl(1), tier = "ask" | "ask_human")`
(IC-53)."""),
]
apply(P, pairs)
