from rep import apply
P = "/Users/wanjun/Desktop/gptr/dev/spec/04-interface-contract.md"
pairs = [
("""stores the pending plan under `home_address(home)` with the time, appends `gptr.plan`, offers the execute menu interactively), and the `plan.pending` service (returns the plan once within the same process and one hour, then marks it used) | P02 load |""",
"""stores the pending plan under `home_address(home)` with the time, appends `gptr.plan`, offers the execute menu interactively), the plan-mode allowlist check (only calls known to be read-only run, IC-54), and the `plan.pending` service (returns the plan once, only to the next top-level `gptr()` call of the same process and environment within one hour; any other call in between discards it; IC-56) | P02 load |"""),
("""| `builtin_system1(gptr)` | `s1-client.R` | registers the provider `typesafe` (base URL `https://api.typesafe.ai/v1/`, key `TYPESAFE_API_KEY`, model alias `jev` -> `jev-latest`, `type = "classifier"`), gateway records of 04 §4, the adapter `typesafe-system-one` (`transport = "http_json"`, `classify`), the adapter `s1-emulate`, the route `classifier` (order 10) and the service `s1.decide` | P02 load |""",
"""| `builtin_system1(gptr)` | `s1-client.R` | registers the provider `typesafe` (base URL `https://api.typesafe.ai/v1/`, key `TYPESAFE_API_KEY`, model alias `jev` -> `jev-latest`, `type = "classifier"`, `rate = list(requests_per_s = 40, tokens_per_s = 1e5)`, IC-64), gateway records of 04 §4, the adapter `typesafe-system-one` (`transport = "http_json"`, `classify`), the adapter `s1-emulate`, the route `classifier` (order 10), the `system1` prompt section (IC-68) and the service `s1.decide`; P13 also owns the example router `inst/gptr/examples/jev-router.R` (IC-69) | P02 load |"""),
("""| `builtin_console(gptr)` | `console-repl.R` | registers the `frontend` `console`, the route `console` (order 30), the renderer hooks (process-wide notify hooks on `message_update`, `message_end`, `tool_execution_start`, `tool_execution_end`, `agent_end` that render only for the foreground session when `verbosity() >= 2`), the service `console.interrupt_policy`, and the command specs of §6.17 of `03` | P02 load |""",
"""| `builtin_console(gptr)` | `console-repl.R` | registers the `frontend` `console`, the route `console` (order 30), the renderer hooks (process-wide notify hooks on `message_update`, `message_end`, `tool_execution_start`, `tool_execution_end`, `agent_end` that render only for the foreground session when `verbosity() >= 2`, a hook on `artifact_start` printing `artifact  <id>  ->  <url>   (running in background)` (NS-8), tool `render` functions and `renderer` records, IC-69, IC-71), the service `console.interrupt_policy`, and the command specs of §6.17 of `03` | P02 load |"""),
("""| `builtin_documents(gptr)` | `doc-formats.R` | registers `doc_format` specs `r`, `rmd`, `qmd`, `ipynb`, `transcript`; the route `document` (order 50); an `agent_end` hook that renders and writes the block when `run$opts$doc` is set; a `session_tree` hook that makes undone blocks inert; the services `doc.site`, `doc.edit` and `doc.s1_block` | P02 load |
| `doc_locate(call)` | `doc-locate.R` | a site `list(kind = "srcref" \\| "source_frame" \\| "knitr" \\| "quarto" \\| "jupyter" \\| "rscript" \\| "ide" \\| "console", path, format, stmt = int(2) \\| NULL, expr = call \\| NULL, occurrence = int(1), ordinal = int(1), backend = chr(1), top_level = lgl(1), ide_id = chr(1) \\| NULL, defer = lgl(1))` using the precedence of §6.9.3 of `03`; `source()` frames are read inside `tryCatch` only when `gptr.doc_source_frames` is `TRUE` | P15 |
| `doc_decide(site, prompt_hash, mode)` | `doc-replay.R` | `"replay"`, `"run"`, `"regenerate"`, `"skip"` (undone), or signals `not_recorded`/`stale_block` per the table of 14 §4.4.2 plus the undone row of G7 §3.8 | P15 |
| `doc_block_lines(session, turn, site, call_ordinal)` | `doc-blocks.R` | chr lines of a block in the §11.5 grammar for the site's format (code of successful `record = TRUE` `r` calls from `details$code`, `#>` outputs from `details$outputs`, `## Decision:` notes, bridge digests, artifact paths, redacted with `code_for_history()` and `persist`) | P15 |
| `doc_upsert(site, block_lines, block_id = NULL)` | `doc-blocks.R` | idempotent insert/replace of the owned block through the site's backend, passing the `document_write` event (fail closed, patchable) first; md5 conflict check with re-locate and retry (3 times, then warning `doc_conflict`); deferred under Rscript; returns `list(action, block_id, lines, backend)` and appends `gptr.doc_block` | P15, P16 |
| `prompt_hash(template)` | `doc-blocks.R` | 12 hex of sha256 of the normalised template (trimws, CRLF -> LF, whitespace around newlines removed) | P15 |""",
"""| `builtin_documents(gptr)` | `doc-formats.R` | registers `doc_format` specs `r`, `rmd`, `qmd`, `ipynb`, `transcript`; the route `document` (order 50); the `documents` prompt section (IC-68); an `agent_end` hook that renders and writes the block when `run$opts$doc` is set; a `session_tree` hook that makes undone blocks inert; the services `doc.site`, `doc.edit` and `doc.s1_block` (owned by `builtin:documents`, so filtering it removes them, IC-34) | P02 load |
| `doc_locate(call)` | `doc-locate.R` | a site `list(kind = "srcref" \\| "source_frame" \\| "knitr" \\| "quarto" \\| "jupyter" \\| "rscript" \\| "ide" \\| "console", path, format, stmt = int(2) \\| NULL, expr = call \\| NULL, occurrence = int(1), ordinal = int(1), backend = chr(1), top_level = lgl(1), in_block = chr(1) \\| NULL (the agent block whose body holds the statement, IC-47), ide_id = chr(1) \\| NULL, defer = lgl(1))` using the precedence of §6.9.3 of `03`; `source()` frames are read inside `tryCatch` only when `gptr.doc_source_frames` is `TRUE`; paths compared with `path_key()` | P15 |
| `doc_decide(site, prompt_hash, args_hash, mode)` | `doc-replay.R` | `"replay"`, `"run"`, `"regenerate"`, `"skip"` (undone), or signals `not_recorded`/`stale_block` per the table of 14 §4.4.2 plus the undone row of G7 §3.8; a block is fresh only when both hashes match (IC-45); block-nested calls replay from S2 (IC-47) | P15 |
| `doc_block_lines(session, turn, site, call_ordinal)` | `doc-blocks.R` | chr lines of a block in the §11.5 grammar for the site's format (code of successful `record = TRUE` `r` calls from `details$code` minus top-level `gptr_return()` calls and calls of `record = FALSE` members, with top-level `<-` rewritten to `=` where safe; `#>` outputs from `details$outputs`; `## Decision:`, `## Steer:` and `## Follow-up:` lines; bridge digests; artifact paths; redacted with `code_for_history()` and `persist`; IC-48, IC-49); team and fan-out blocks per IC-47; plan-mode turns give one `## Plan:` line | P15 |
| `doc_upsert(site, block_lines, block_id = NULL)` | `doc-blocks.R` | checks write consent (IC-45; otherwise nothing is written), then idempotent insert/replace of the owned block through the site's backend, passing the `document_write` event (fail closed, patchable) first; md5 conflict check with re-locate and retry (3 times, then warning `doc_conflict`); deferred under Rscript through the sidecar of IC-51; never writes an open notebook (IC-50); returns `list(action, block_id, lines, backend)` and appends `gptr.doc_block`; caches child texts in S2 (IC-47) | P15, P16 |
| `prompt_hash(template)`, `args_hash(interp)` | `doc-blocks.R` | 12 hex of sha256 of the normalised template (trimws, CRLF -> LF, whitespace around newlines removed); 8 hex of sha256 of the sorted interpolated `name=value` pairs, `NULL` without interpolation (IC-45) | P15 |"""),
("""| `skill_discover(scope = "all")` | `skill-discover.R` | df of skills from the roots of 16 §4.8 (`.gptr/skills`, `.agents/skills`, `.claude/skills` of trusted projects; user directories; attached packages' `inst/gptr/skills` and `inst/skills`; plugin `skills/`), bounded walk | P17 |""",
"""| `skill_discover(scope = "all")` | `skill-discover.R` | df of skills from the roots of 16 §4.8 (`.gptr/skills`, `.agents/skills`, `.claude/skills` of trusted projects; user directories under `user_home()`; attached packages' `inst/gptr/skills` and `inst/skills`; plugin `skills/`), bounded walk; untrusted project skills are listed but never catalogued (IC-52); names compared with `name_norm()` (IC-42) | P17 |"""),
("""| `skill_parse(path)` | `skill-discover.R` | `<spec:skill>` from `SKILL.md` frontmatter (lenient yaml: `name`, `description` <= 1,024 characters, `disable-model-invocation`, `allowed-tools`) or `NULL` + diagnostic | P17 |""",
"""| `skill_parse(path)` | `skill-discover.R` | `<spec:skill>` from `SKILL.md` frontmatter (lenient yaml: `name`, `description` <= 1,024 characters, `disable-model-invocation`, `allowed-tools`; string keys keep their source text against YAML 1.1 coercion, IC-71) or `NULL` + diagnostic; the catalog shows `[skill:<name>/SKILL.md]` pseudo-paths that `read` resolves (IC-68) | P17 |"""),
("""| `mcp_connect(spec)` | `mcp-client.R` | a `gptr_mcp_conn` (era probe with `gptr.mcp_probe_timeout`, cached per spec hash for 7 days; stdio through `proc_spawn()` with `child_env("mcp")` + the spec's expanded `env`; HTTP on the reactor) | P18 |""",
"""| `mcp_connect(spec)` | `mcp-client.R` | a `gptr_mcp_conn` (era probe with `gptr.mcp_probe_timeout`, cached per spec hash for 7 days; stdio through `proc_spawn()` with `child_env("mcp")` + the spec's expanded `env`, stderr read by gptr and appended redacted to `tempdir()/gptr/mcp-logs/` unless `gptr.mcp_debug`, IC-70; HTTP on the reactor with `followlocation = 0L`) | P18 |"""),
("""| `mcp_dispatch_local(message, session)` (service) | `mcp-server.R` | answers one JSON-RPC message (both eras) with the session's `r`, `read`, `edit`, `write` through `dispatch_nested()`-equivalent gating; returns the response list | P20 |
| `oauth_flow(issuer_or_provider, scopes, client)` | `auth-oauth.R` | PKCE S256, loopback or paste callback, locked refresh; tokens registered as secrets | P18 |""",
"""| `mcp_dispatch_local(message, session)` (service) | `mcp-server.R` | answers one JSON-RPC message (both eras) with the session's `r`, `read`, `edit`, `write` through `dispatch_nested()`-equivalent gating, evaluating in the session's run evaluation environment with its mode and rules; the single gate for the claude route (IC-65); returns the response list | P20 (through `opts$mcp_dispatch`, IC-33) |
| `mcp_serve_token(session)` | `mcp-server.R` | issues a bearer token bound to `session` on the shared server and revokes it when the session's child exits (behind `mcp.serve_ensure`, IC-58) | P18 |
| `oauth_flow(issuer_or_provider, scopes, client)` | `auth-oauth.R` | PKCE S256, loopback (port from `port_candidates()`) or paste callback, locked refresh; refuses authorization-server metadata without `code_challenge_methods_supported` or without S256; validates `iss` (RFC 9207) when advertised with gptr's own callback reader; state and redirect checks (IC-71); tokens registered as secrets | P18 |"""),
("""| `builtin_subagents(gptr)` | `subagent-backends.R` | registers `backend` specs `inline`, `worker`, `cli` and the routes `team` (order 40) and `fanout` (order 45) | P02 load |""",
"""| `builtin_subagents(gptr)` | `subagent-backends.R` | registers `backend` specs `inline`, `worker`, `cli` (the `cli` backend's tests are P20's, IC-36), the routes `team` (order 15) and `fanout` (order 16) (IC-39), and the `r_session` fragment for sub-agents (IC-68) | P02 load |"""),
("""starts a child through the backend: `spec` = `list(agent = <spec:agent>, prompt, context (list of call items), model, mode, depth, export, objects, preset, rng_stream)`; returns a handle `list(session = <session>, fds = function() int, poll = function() NULL, cancel = function() NULL)`; enforces the limits of §6.13 of `03` | P19 |""",
"""starts a child through the backend: `spec` = `list(agent = <spec:agent>, prompt, context (list of call items), model, mode, depth, export, objects, preset, rng_state, registry)`; returns a handle `list(session = <session>, fds = function() int, poll = function() NULL, cancel = function() NULL)`; enforces the limits of §6.13 of `03` (`max_tasks` only at depth >= 1, IC-39; pools capped at 2 under check, IC-60); budget charged to the root (IC-66) | P19 |"""),
("""| `worker_main(spec_path, result_path)` | `subagent-worker.R` | runs inside a callr child: reads the spec (`readRDS`), runs `gptr()` with the `jsonl` frontend on stdout and answers on stdin (§11.11), saves exports with `save_rds()` | P19 (callr) |""",
"""| `worker_main(spec_path, result_path)` | `subagent-worker.R` | runs inside a callr child (started with `supervise_default()`, `encoding = "UTF-8"` and `child_env_callr(child_env("worker"))`): reads the spec (`readRDS`), re-registers `spec$registry` (IC-69), runs `gptr()` with the `jsonl` frontend on stdout and answers on stdin (§11.11), exits on stdin EOF, EPIPE or a dead parent pid (checked every 5 s, IC-60), saves exports with `save_rds()` | P19 (callr) |"""),
("""| `cli_find(cli = c("claude", "codex"))` | `cli-common.R` | path (native binaries preferred; `.cmd` shims allowed through the process engine) or `gptr_error_cli_missing` | P20 |
| `cli_version(path)` | `cli-common.R` | `package_version` from `--version` (cached per path and mtime); below the minimum (`claude` >= 2.0.0) signals `gptr_error_cli_version` | P20 (the providers' `status()` functions that `gptr_providers()` calls) |""",
"""| `cli_find(cli = c("claude", "codex"))` | `cli-common.R` | path from `gptr.cli_path`, then PATH, then the per-OS known locations of IC-65; native binaries only for claude (the npm `claude.cmd` shim is refused with an install hint); `gptr_error_cli_missing` otherwise | P20 |
| `cli_version(path)`, `cli_probe(path)` | `cli-common.R` | `package_version` from `--version` and a capability probe of `--help` (cached per path and mtime; run only on first use or `check = TRUE`); below the minimum (`claude` >= 2.0.0), or a `-p` that defaults to `--bare` without a documented opt-out, signals `gptr_error_cli_version` | P20 (`status()` reads the cache only unless `gptr_providers(check = TRUE)`, IC-65) |"""),
("""| `bg_register(s)` (service `bg.register`) | `agent-background.R` | requires later (`gptr_error_missing_package`); marks the run background, adds a `session` job, ensures the `later` pump (50 ms timer calling `reactor_pump(slice_ms = 0)`); R tools of background runs run at idle ticks (`gptr.background_tools = "idle"`) or wait for `gptr_wait()` | P08, P14 (`[b]ackground`) |
| `gptr_jobs()` | `agent-background.R` | §6.5 | users |""",
"""| `bg_register(s)` (service `bg.register`) | `agent-background.R` | requires later (`gptr_error_missing_package`); marks the run background, adds a `session` job, ensures the `later` pump (50 ms timer calling `reactor_pump(slice_ms = 0)`, a no-op while the reactor is on the stack, IC-57); R tools of background runs run at idle ticks (`gptr.background_tools = "idle"`) or wait for `gptr_wait()`; an ask moves the run to `waiting` and is shown at the next blocking gptr call; a tool that changed bindings at an idle tick prints one notice | P08, P14 (`[b]ackground`) |"""),
("""| `builtin_bridges(gptr)` | `bridge-sh.R` | defines the `interpreter` kind (`kind` spec, IC-02), registers built-in interpreters (`.sh`, `.py`, `.R`, `.js`, `.pl`, `.rb`, `.jl`) and the members `sh`, `script`, `bg`, `jobs`, `out` (§9.4); emits `bridge_call` | P02 load |
| `builtin_lang(gptr)` | `bridge-lang.R` | registers the members `py`, `sql`, `knit` | P02 load |""",
"""| `builtin_bridges(gptr)` | `bridge-sh.R` | defines the `interpreter` kind (`kind` spec, IC-02), registers built-in interpreters (`.sh`, `.py`, `.R`, `.js`, `.pl`, `.rb`, `.jl`), the members `sh`, `script`, `bg`, `jobs` (§9.4; `out` is P10's, IC-36) and the `r_session` shell fragment (IC-68); emits `bridge_call` | P02 load |
| `builtin_lang(gptr)` | `bridge-lang.R` | registers the members `py`, `sql`, `knit` (shell engines routed through `gptr$sh()`, IC-67) and the `r_session` languages fragment | P02 load |"""),
("""| `builtin_artifacts(gptr)` | `artifact-app.R` | registers `artifact_type` specs `shiny` and `html`, the member `app` (§9.4) and the `artifacts` checkpointer (the `artifacts` prompt section is P07's, shown when `app` is registered) | P02 load |
| `artifact_serve(dir, port_file, parent_pid)` | `artifact-app.R` | runs inside the callr child: picks a random free 127.0.0.1 port, publishes it by atomic rename of `port_file`, starts a parent-PID watchdog, runs the app | P23 (callr) |""",
"""| `builtin_artifacts(gptr)` | `artifact-app.R` | registers `artifact_type` specs `shiny` and `html`, the member `app` (§9.4), the `artifacts` prompt section (IC-68) and the `artifacts` checkpointer | P02 load |
| `artifact_serve(dir, port_file, parent_pid, token)` | `artifact-app.R` | runs inside the callr child: picks a free 127.0.0.1 port from `port_candidates()`, publishes it by atomic rename of `port_file`, starts a parent-PID watchdog, runs the app behind the `gptr_token` check (IC-71); stdout/stderr are read by the parent and appended redacted to `app-vNNN.log` (IC-70) | P23 (callr) |"""),
]
apply(P, pairs)
