# Tests for R/bridge-sh.R (P22): command resolution and views, gptr_cmd results, scripts and the
# interpreter kind, background jobs, builtin:bridges.

test_that("simple command lines split into words and shell syntax does not", {
  expect_identical(bridge_split("git status --porcelain"), c("git", "status", "--porcelain"))
  expect_identical(bridge_split("echo 'quoted words' plain"), c("echo", "quoted words", "plain"))
  expect_identical(bridge_split("printf \"a b\""), c("printf", "a b"))
  expect_identical(bridge_split("Rscript -e 'cat(1)' \"a|b\""), c("Rscript", "-e", "cat(1)", "a|b"))
  expect_identical(bridge_split("rm\v-rf\f/"), "rm\v-rf\f/")
  expect_null(bridge_split("ls | head"))
  expect_null(bridge_split("echo $HOME"))
  expect_null(bridge_split("FOO=1 make"))
  expect_null(bridge_split("cat ~/x"))
  expect_null(bridge_split("echo \"$USER\""))
  expect_null(bridge_split("echo 'open"))
  expect_null(bridge_split("make > log.txt"))
  expect_null(bridge_split("   "))
})

test_that("argv vectors, simple lines and shell lines resolve differently", {
  r = bridge_resolve(c("git", "status"))
  expect_identical(r[c("command", "args", "via")], list(command = "git", args = "status",
                                                        via = "argv"))
  expect_identical(bridge_resolve(c("Rscript", "-e", "1"))$command, rscript_path())
  skip_on_os("windows")
  d = bridge_resolve(paste(shQuote(rscript_path()), "--version"))
  expect_identical(d$via, "direct")
  expect_identical(d$command, rscript_path())
  expect_identical(d$args, "--version")
  s = bridge_resolve("echo a | sort")
  sh = shell_resolve("echo a | sort")
  expect_identical(s$via, "shell")
  expect_identical(s$command, sh$command)
  expect_identical(s$args, sh$args)
  expect_identical(bridge_resolve("gptr-no-such-program-p22 --flag")$via, "shell")
})

test_that("validated JSON arrays flatten back to character vectors", {
  expect_identical(bridge_chr(list("git", "status")), c("git", "status"))
  expect_identical(bridge_chr("ls"), "ls")
  expect_null(bridge_chr(NULL))
  expect_identical(bridge_chr(list()), character())
  expect_identical(bridge_chr(list(1, 2)), list(1, 2))
  expect_identical(bridge_chr(list(GIT_DIR = ".git")), c(GIT_DIR = ".git"))
})

test_that("views keep head and tail within the budget and name the out id", {
  lines = sprintf("line %05d of the output with some words", 1:20000)
  v = bridge_view_lines(lines, 300L, id = "o1a2b3c")
  expect_lte(est_tokens(v, "r_output"), 300)
  expect_identical(v[[1L]], lines[[1L]])
  expect_identical(v[[length(v)]], lines[[20000L]])
  notice = grep("lines omitted", v, value = TRUE, fixed = TRUE)
  expect_length(notice, 1L)
  expect_match(notice, "all: peter$out(\"o1a2b3c\")]", fixed = TRUE)
  omitted = as.integer(sub("^\\[\\.\\.\\. ([0-9]+) lines.*$", "\\1", notice))
  expect_identical(omitted + length(v) - 1L, 20000L)
  share = (match(notice, v) - 1) / (length(v) - 1)
  expect_gt(share, 0.3)
  expect_lt(share, 0.5)
  expect_identical(bridge_view_lines(c("a", "b"), 300L), c("a", "b"))
  expect_identical(bridge_view_lines(character(), 300L), character())
  e = bridge_view_lines(lines, 250L, head = 0.2, id = "o9", stream = "stderr")
  expect_match(grep("omitted", e, value = TRUE), "peter$out(\"o9\", \"stderr\")", fixed = TRUE)
  expect_identical(bridge_notice(3L), "[... 3 lines omitted]")
})

test_that("the print budget is the option, capped at 0.6 x the r budget inside a run", {
  expect_identical(bridge_budget(NULL), 1500L)
  expect_identical(bridge_budget(120), 120L)
  local_gptr_options(helper_output_tokens = 900L)
  expect_identical(bridge_budget(NULL), 900L)
  testthat::local_mocked_bindings(run_current = function() list(session = "s0000000001"))
  local_gptr_options(helper_output_tokens = 1500L, r_output_tokens = 1000L)
  expect_identical(bridge_budget(NULL), 600L)
  expect_identical(bridge_budget(2000), 2000L)
})

test_that("labels are one line of at most 50 characters", {
  expect_identical(bridge_label(c("git", "status", "--porcelain")), "git status --porcelain")
  long = bridge_label(paste(rep("word", 30), collapse = "  "))
  expect_identical(nchar(long), 50L)
  expect_true(endsWith(long, "..."))
})
