test_that("the catalogue lists the 46 events of contract 10.4 with their semantics", {
  cat = ev_catalogue()
  expect_named(cat, c("event", "semantics", "fail_closed", "payload", "returns", "origin"))
  expect_equal(nrow(cat), 46L)
  expect_equal(anyDuplicated(cat$event), 0L)
  expect_setequal(cat$event[cat$fail_closed],
                  c("tool_call", "permission_request", "document_write"))
  expect_true(all(cat$semantics %in% c("notify", "collect", "transform", "decision",
                                       "first_decision", "patch", "block_patch")))
  expect_true(all(cat$origin %in% c("pi", "gptr")))
  expect_equal(cat$origin[cat$event == "request_params"], "gptr")
  expect_equal(cat$origin[cat$event == "tool_call"], "pi")
  expect_equal(ev_semantics("tool_call"), "decision")
  expect_equal(ev_semantics("tool_result"), "patch")
  expect_equal(ev_semantics("request_params"), "patch")
  expect_equal(ev_semantics("input"), "transform")
  expect_equal(ev_semantics("session_start"), "collect")
  expect_equal(ev_semantics("resources_discover"), "collect")
  expect_equal(ev_semantics("permission_request"), "first_decision")
  expect_equal(ev_semantics("project_trust"), "first_decision")
  expect_equal(ev_semantics("document_write"), "block_patch")
  expect_equal(ev_semantics("myplugin:done"), "notify")
  expect_null(ev_semantics("PreToolUse"))
})

test_that("Claude, Codex, pre-IC-03 and unported names are refused with a hint", {
  err = expect_error(ev_check_name("PreToolUse"), class = "gptr_error_invalid_argument")
  expect_match(conditionMessage(err), "did you mean 'tool_call'?", fixed = TRUE)
  expect_equal(err$arg, "event")
  err = expect_error(ev_check_name("session_end"), class = "gptr_error_invalid_argument")
  expect_match(conditionMessage(err), "session_shutdown", fixed = TRUE)
  err = expect_error(ev_check_name("context"), class = "gptr_error_invalid_argument")
  expect_match(conditionMessage(err), "not ported", fixed = TRUE)
  err = expect_error(ev_check_name("Tool_Call"), class = "gptr_error_invalid_argument")
  expect_match(conditionMessage(err), "did you mean 'tool_call'?", fixed = TRUE)
  expect_error(ev_check_name("no_such_event"), class = "gptr_error_invalid_argument")
  expect_error(ev_check_name(NA_character_), class = "gptr_error_invalid_argument")
  expect_error(ev_check_name(c("a", "b")), class = "gptr_error_invalid_argument")
  expect_equal(ev_check_name("tool_call"), "tool_call")
  expect_equal(ev_check_name("myplugin:done"), "myplugin:done")
  expect_true(ev_is_channel("my.plugin:topic-1"))
  expect_false(ev_is_channel("tool_call"))
  expect_false(ev_is_channel("a:b:c"))
})
