# tests/testthat/test-ckpt-files.R -- the blob store, garbage collection, the tracker and the
# guarded 3-way restores (P16).

blob_count = function() {
  length(list.files(file.path(workspace_root(create = FALSE), "checkpoints", "blobs"),
                    recursive = TRUE))
}

test_that("the blob store deduplicates, compresses small text and restores atomically", {
  proj = local_project()
  f = file.path(proj, "a.R")
  writeLines(c("x = 1", "y = 2"), f)
  h = ckpt_store_put(f)
  expect_match(h, "^[0-9a-f]{32}$")
  blob = ckpt_blob_find(h)
  expect_true(endsWith(blob, ".gz"))
  expect_match(blob, "/.gptr/checkpoints/blobs/", fixed = TRUE)
  n0 = blob_count()
  f2 = file.path(proj, "copy.R")
  file.copy(f, f2)
  expect_identical(ckpt_store_put(f2), h)
  expect_identical(blob_count(), n0)
  writeLines("changed", f)
  expect_true(ckpt_store_get(h, f))
  expect_identical(readLines(f), c("x = 1", "y = 2"))
  expect_false(ckpt_store_get(strrep("0", 32L), f))
  expect_false(ckpt_store_get("../../copy.R", file.path(proj, "out.R")))
  expect_identical(ckpt_store_put(character()), character())
})

test_that("already-compressed files are stored raw and come back byte for byte", {
  proj = local_project()
  f = file.path(proj, "d.rds")
  saveRDS(1:10, f)
  h = ckpt_store_put(f)
  expect_false(endsWith(ckpt_blob_find(h), ".gz"))
  out = file.path(proj, "restored", "d.rds")
  expect_true(ckpt_store_get(h, out))
  expect_identical(readBin(out, "raw", 1e4), readBin(f, "raw", 1e4))
  g = file.path(proj, "e.rds")
  saveRDS(11:20, g)
  blobs = dirname(ckpt_blob_path(hash_file(g), ""))
  dir.create(blobs, showWarnings = FALSE)
  Sys.chmod(blobs, "0555", use_umask = FALSE)
  withr::defer(Sys.chmod(blobs, "0755", use_umask = FALSE))
  skip_if(file.access(blobs, 2L) == 0L, "the directory stays writable")
  expect_error(suppressWarnings(ckpt_store_put(g)), class = "gptr_error_workspace")
})

test_that("without a workspace the store lives under tempdir(), never in the project", {
  proj = local_project(gptr = FALSE)
  f = file.path(proj, "a.txt")
  writeLines("a", f)
  h = ckpt_store_put(f)
  expect_true(startsWith(path_norm(ckpt_blob_find(h)), path_norm(tempdir())))
  expect_false(dir.exists(file.path(proj, ".gptr")))
})

test_that("blob GC keeps referenced and young blobs and deletes old unreferenced ones", {
  proj = local_project()
  root = workspace_root(create = FALSE)
  make = function(txt) {
    f = tempfile(fileext = ".txt", tmpdir = proj)
    writeLines(txt, f)
    ckpt_store_put(f)
  }
  h_ref = make("referenced")
  h_old = make("old and unreferenced")
  h_new = make("young and unreferenced")
  old = Sys.time() - 40 * 86400
  Sys.setFileTime(ckpt_blob_find(h_ref), old)
  Sys.setFileTime(ckpt_blob_find(h_old), old)
  Sys.setFileTime(ckpt_blob_find(h_new), old)
  expect_identical(make("young and unreferenced"), h_new)
  sdir = file.path(root, "sessions")
  writeLines(c('{"type":"session","version":3,"id":"s0000000001"}',
               paste0('{"type":"custom","id":"a1b2c3d4","parentId":null,',
                      '"customType":"gptr.checkpoint","data":{"fragments":{"files":{"files":[',
                      '{"path":"a.R","pre":"', h_ref, '"}]}}}}')),
             file.path(sdir, "20260930T000000_s0000000001.jsonl"))
  stale = file.path(root, "checkpoints", "blobs", "ab", paste0(strrep("ab", 16L), ".tmp-1"))
  dir.create(dirname(stale), showWarnings = FALSE)
  writeLines("interrupted", stale)
  Sys.setFileTime(stale, old)
  spills = file.path(root, "checkpoints", "objects", c("s0000000001", "s0000000099"))
  for (d in spills) dir.create(d, recursive = TRUE)
  Sys.setFileTime(spills, old)
  res = ckpt_gc(root, days = 30)
  expect_false(file.exists(stale))
  expect_false(res$skipped)
  expect_identical(res$deleted, 1L)
  expect_false(is.null(ckpt_blob_find(h_ref)))
  expect_null(ckpt_blob_find(h_old))
  expect_false(is.null(ckpt_blob_find(h_new)))
  expect_identical(dir.exists(spills), c(TRUE, FALSE))
  idx = jsonlite::fromJSON(file.path(root, "checkpoints", "index.json"), simplifyVector = FALSE)
  expect_setequal(names(idx$blobs), c(h_ref, h_new))
  local_gptr_options(quiet = FALSE, checkpoint_disk_bytes = 1)
  expect_message(ckpt_gc(root, days = 30), "above gptr.checkpoint_disk_bytes",
                 class = "gptr_message_notice")
})

test_that("blob GC skips while another live process holds a session lock (IC-71)", {
  proj = local_project()
  root = workspace_root(create = FALSE)
  f = withr::local_tempfile(fileext = ".txt")
  writeLines("old and unreferenced", f)
  h_old = ckpt_store_put(f)
  Sys.setFileTime(ckpt_blob_find(h_old), Sys.time() - 40 * 86400)
  sf = file.path(root, "sessions", "20260930T000000_s0000000002.jsonl")
  writeLines('{"type":"session","version":3,"id":"s0000000002"}', sf)
  dir.create(paste0(sf, ".lock"))
  writeLines(c("999999", "1790000000.5"), file.path(paste0(sf, ".lock"), "pid"))
  local_mocked_bindings(pid_alive = function(pid, create_time = NULL) TRUE)
  res = ckpt_gc(root, days = 30)
  expect_true(res$skipped)
  expect_false(is.null(ckpt_blob_find(h_old)))
  local_mocked_bindings(pid_alive = function(pid, create_time = NULL) FALSE)
  res = ckpt_gc(root, days = 30)
  expect_false(res$skipped)
  expect_null(ckpt_blob_find(h_old))
})

test_that("pruning in one process keeps the blobs another live process's session references", {
  skip_on_cran()
  proj = local_project()
  root = workspace_root(create = FALSE)
  f = withr::local_tempfile(fileext = ".txt")
  writeLines("held by the other session", f)
  h = ckpt_store_put(f)
  Sys.setFileTime(ckpt_blob_find(h), Sys.time() - 40 * 86400)
  other = processx::process$new(rscript_path(), c("--vanilla", "-e", "Sys.sleep(60)"))
  withr::defer(other$kill())
  sf = file.path(root, "sessions", "20260930T000000_s0000000003.jsonl")
  writeLines(c('{"type":"session","version":3,"id":"s0000000003"}',
               paste0('{"type":"custom","id":"b1c2d3e4","parentId":null,',
                      '"customType":"gptr.checkpoint","data":{"fragments":{"files":{"files":[',
                      '{"path":"x.R","pre":"', h, '"}]}}}}')), sf)
  dir.create(paste0(sf, ".lock"))
  writeLines(c(as.character(other$get_pid()), ""), file.path(paste0(sf, ".lock"), "pid"))
  expect_true(ckpt_gc(root, days = 30)$skipped)
  other$kill()
  other$wait(5000)
  res = ckpt_gc(root, days = 30)
  expect_false(res$skipped)
  expect_false(is.null(ckpt_blob_find(h)))
})

paths_status = function(frag) {
  stats::setNames(vapply(frag$files, function(r) r$status, ""),
                  vapply(frag$files, function(r) r$path, ""))
}

test_that("the walk prunes .git and .gptr and lists links unfollowed; restores avoid them", {
  skip_on_os("windows")
  proj = local_project(files = list("R/a.R" = "a = 1", ".git/config" = "[core]",
                                    ".hg/dirstate" = "v1", ".svn/wc.db" = "v1",
                                    "data/x.csv" = "id"))
  file.symlink(file.path(proj, "data"), file.path(proj, "data_link"))
  w = ckpt_walk(proj)
  expect_setequal(w$path, c("R/a.R", "data/x.csv", "data_link"))
  expect_true(w$link[w$path == "data_link"])
  expect_identical(is.na(ckpt_walked(list(root = proj), file.path(proj, "Node_Modules", "x.js"))),
                   fs_case_insensitive(proj))
  g = ckpt_restore_guard(file.path(proj, "data_link", "x.csv"))
  expect_false(g$ok)
  expect_match(g$reason, "symbolic link")
})

test_that("the checkpoint store is never walked, also where it lies inside the project", {
  proj = local_project(gptr = FALSE, files = list("a.R" = "a = 1"))
  store = file.path(proj, "tmp[1]", "gptr")
  local_mocked_bindings(workspace_root = function(create = TRUE) {
    if (create) dir.create(store, recursive = TRUE, showWarnings = FALSE)
    store
  })
  ck = ckpt_ck_new("s0000000033")
  call = list(id = "c1", name = "r", input = list(code = "x"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("a = 2", file.path(proj, "a.R"))
  frag = ckpt_files_after(ck, call, tok)
  expect_identical(paths_status(frag), c(a.R = "modified"))
  expect_true(ckpt_files_undo(ck, frag)$ok)
  expect_identical(readLines(file.path(proj, "a.R")), "a = 1")
})

test_that("a mutating step records created, modified and deleted files; undo and redo swap them", {
  proj = local_project(files = list("R/a.R" = "f = function(x) x + 1",
                                    "notes.md" = c("# Notes", "keep me")))
  ck = ckpt_ck_new("s0000000021")
  call = list(id = "c1", name = "r",
              input = list(code = "write.csv(data.frame(id = 1:3), 'out.csv')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  expect_true(all(c("R/a.R", "notes.md") %in% names(ck$files$hash)))
  writeLines("f = function(x) x + 10", file.path(proj, "R", "a.R"))
  utils::write.csv(data.frame(id = 1:3), file.path(proj, "out.csv"), row.names = FALSE)
  file.remove(file.path(proj, "notes.md"))
  frag = ckpt_files_after(ck, call, tok)
  st = paths_status(frag)
  expect_identical(st[["out.csv"]], "created")
  expect_identical(st[["R/a.R"]], "modified")
  expect_identical(st[["notes.md"]], "deleted")
  expect_silent(json_encode(frag))
  expect_identical(ckpt_files_describe(frag), c("file out.csv: created", "file R/a.R: modified",
                                                "file notes.md: deleted"))
  u = ckpt_files_undo(ck, frag)
  expect_true(all(u$ok))
  expect_false(file.exists(file.path(proj, "out.csv")))
  expect_identical(readLines(file.path(proj, "R", "a.R")), "f = function(x) x + 1")
  expect_identical(readLines(file.path(proj, "notes.md")), c("# Notes", "keep me"))
  r = ckpt_files_undo(ck, frag, redo = TRUE)
  expect_true(all(r$ok))
  expect_true(file.exists(file.path(proj, "out.csv")))
  expect_identical(readLines(file.path(proj, "R", "a.R")), "f = function(x) x + 10")
  expect_false(file.exists(file.path(proj, "notes.md")))
})

test_that("files changed by a child process are recorded too", {
  skip_on_cran()
  proj = local_project(files = list("R/b.R" = "h = function() 'b'"))
  ck = ckpt_ck_new("s0000000022")
  call = list(id = "c1", name = "r", input = list(code = "system2('Rscript', 'job.R')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  processx::run(rscript_path(), c("--vanilla", "-e", "writeLines('child', 'R/b.R')"),
                wd = proj)
  frag = ckpt_files_after(ck, call, tok)
  expect_identical(paths_status(frag)[["R/b.R"]], "modified")
  u = ckpt_files_undo(ck, frag)
  expect_true(all(u$ok))
  expect_identical(readLines(file.path(proj, "R", "b.R")), "h = function() 'b'")
})

test_that("undo keeps a file edited after the turn (3-way) unless forced", {
  proj = local_project(files = list("b.R" = "h = function() 'b'"))
  ck = ckpt_ck_new("s0000000023")
  call = list(id = "c1", name = "write", input = list(path = "b.R", content = "child"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("h = function() 'agent'", file.path(proj, "b.R"))
  frag = ckpt_files_after(ck, call, tok)
  writeLines("h = function() 'user edit'", file.path(proj, "b.R"))
  u = ckpt_files_undo(ck, frag)
  expect_false(u$ok)
  expect_match(u$action, "conflict")
  expect_identical(readLines(file.path(proj, "b.R")), "h = function() 'user edit'")
  expect_identical(ckpt_files_undo(ck, frag, dry = TRUE)$ok, FALSE)
  u = ckpt_files_undo(ck, frag, force = TRUE)
  expect_true(u$ok)
  expect_identical(readLines(file.path(proj, "b.R")), "h = function() 'b'")
})

test_that("files over the capture cap and symbolic links are not restorable", {
  skip_on_os("windows")
  local_gptr_options(checkpoint_track_file_max = 10, checkpoint_capture_max = 10)
  proj = local_project(files = list("big.txt" = "0123456789ABCDEF", "notes.md" = "small"))
  file.symlink(file.path(proj, "notes.md"), file.path(proj, "link.md"))
  ck = ckpt_ck_new("s0000000024")
  call = list(id = "c1", name = "r", input = list(code = "cat('x', file = 'big.txt')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("0123456789ABCDEFGH", file.path(proj, "big.txt"))
  writeLines("longer text", file.path(proj, "notes.md"))
  frag = ckpt_files_after(ck, call, tok)
  rows = stats::setNames(frag$files, vapply(frag$files, function(r) r$path, ""))
  expect_false(rows[["big.txt"]]$restorable)
  expect_match(rows[["big.txt"]]$reason, "no pre-image")
  expect_false(rows[["link.md"]]$restorable)
  expect_match(rows[["link.md"]]$reason, "symbolic link")
  expect_true("file link.md: modified (not restorable)" %in% ckpt_files_describe(frag))
  u = ckpt_files_undo(ck, frag)
  expect_identical(u$ok[u$item == "file link.md"], FALSE)
  expect_true(nzchar(Sys.readlink(file.path(proj, "link.md"))))
})

test_that("undo restores mode bits; old rows, later edits and missing copies are not written", {
  skip_on_os("windows")
  local_gptr_options(checkpoint_capture_max = 10)
  proj = local_project(files = list("a.R" = "a = 1", "run.sh" = "echo"))
  Sys.chmod(file.path(proj, "run.sh"), "0750", use_umask = FALSE)
  ck = ckpt_ck_new("s0000000029")
  ckpt_files_sync(ckpt_files_tr(ck))
  Sys.chmod(file.path(proj, "a.R"), "0700", use_umask = FALSE)
  call = list(id = "c1", name = "r", input = list(code = "file.remove('run.sh')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("a = 22", file.path(proj, "a.R"))
  writeLines("a longer new file", file.path(proj, "new.txt"))
  file.remove(file.path(proj, "run.sh"))
  frag = ckpt_files_after(ck, call, tok)
  expect_match(ckpt_files_undo(ck, frag, turn_now = 101L)$action, "older than", all = TRUE)
  expect_true(all(ckpt_files_undo(ck, frag)$ok))
  expect_identical(format(file.mode(file.path(proj, c("run.sh", "a.R")))), c("750", "700"))
  writeLines("a = 3", file.path(proj, "a.R"))
  r = ckpt_files_undo(ck, frag, redo = TRUE)
  expect_identical(r$action[r$item == "file new.txt"], "not redone (no stored copy)")
  expect_match(r$action[r$item == "file a.R"], "conflict: changed after the undo")
  expect_identical(readLines(file.path(proj, "a.R")), "a = 3")
  expect_false(file.exists(file.path(proj, "new.txt")))
})

test_that("a file that cannot be written or read is an item and the undo goes on", {
  skip_on_os("windows")
  proj = local_project(files = list("ro/a.R" = "a = 1", "b.R" = "b = 1", "c.R" = "c = 1"))
  ck = ckpt_ck_new("s0000000031")
  call = list(id = "c1", name = "r", input = list(code = "x"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("a = 2", file.path(proj, "ro", "a.R"))
  writeLines("b = 2", file.path(proj, "b.R"))
  writeLines("c = 2", file.path(proj, "c.R"))
  frag = ckpt_files_after(ck, call, tok)
  Sys.chmod(file.path(proj, "ro"), "0555", use_umask = FALSE)
  withr::defer(Sys.chmod(file.path(proj, "ro"), "0755", use_umask = FALSE))
  Sys.chmod(file.path(proj, "c.R"), "0000", use_umask = FALSE)
  skip_if(file.access(file.path(proj, "ro"), 2L) == 0L, "the directory stays writable")
  u = ckpt_files_undo(ck, frag)
  expect_identical(u$action[u$item == "file ro/a.R"],
                   "not restored (the file could not be changed)")
  expect_match(u$action[u$item == "file c.R"], "conflict")
  expect_identical(readLines(file.path(proj, "b.R")), "b = 1")
})

test_that("undo and redo of a case-only rename keep the file", {
  proj = local_project(files = list("readme.md" = "hello"))
  skip_if_not(fs_case_insensitive(proj), "the file system is case-sensitive")
  ck = ckpt_ck_new("s0000000032")
  call = list(id = "c1", name = "r", input = list(code = "file.rename('readme.md', 'README.md')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  file.rename(file.path(proj, "readme.md"), file.path(proj, "README.md"))
  frag = ckpt_files_after(ck, call, tok)
  expect_true(all(ckpt_files_undo(ck, frag)$ok))
  expect_identical(list.files(proj), "readme.md")
  expect_true(all(ckpt_files_undo(ck, frag, redo = TRUE)$ok))
  expect_identical(list.files(proj), "README.md")
  expect_identical(readLines(file.path(proj, "README.md")), "hello")
})

test_that("a path outside the project and tempdir() is restored only after a human confirms", {
  proj = local_project()
  outside = withr::local_tempdir()
  local_mocked_bindings(ckpt_temp_root = function() file.path(tempdir(), "not-this-one"))
  out = path_norm(file.path(outside, "result.csv"))
  writeLines("old", out)
  ck = ckpt_ck_new("s0000000025")
  call = list(id = "c9", name = "r",
              input = list(code = paste0("writeLines('new', '", out, "')")))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("new", out)
  frag = ckpt_files_after(ck, call, tok)
  row = frag$files[[1L]]
  expect_true(row$abs)
  expect_identical(row$status, "modified")
  u = ckpt_files_undo(ck, frag)
  expect_false(u$ok)
  expect_match(u$action, "not confirmed")
  expect_identical(readLines(out), "new")
  expect_true(is.na(ckpt_files_undo(ck, frag, dry = TRUE)$ok))
  local_scripted_ui(answers = list(1L))
  u = ckpt_files_undo(ck, frag)
  expect_true(u$ok)
  expect_identical(readLines(out), "old")
})

test_that("a planted record pointing outside the project is not restored without a human", {
  proj = local_project()
  outside = withr::local_tempdir()
  local_mocked_bindings(ckpt_temp_root = function() file.path(tempdir(), "not-this-one"))
  target = path_norm(file.path(outside, "victim.txt"))
  writeLines("current", target)
  src = file.path(proj, "planted.txt")
  writeLines("planted", src)
  h = ckpt_store_put(src)
  ck = ckpt_ck_new("s0000000026")
  frag = list(id = "kplanted", turn = 1L, root = path_norm(outside),
              files = list(ckpt_file_row("victim.txt", FALSE, "modified", h,
                                         unname(hash_file(target)), 420, 8, 0, TRUE, "")))
  u = ckpt_files_undo(ck, frag)
  expect_false(u$ok)
  expect_match(u$action, "not confirmed")
  expect_identical(readLines(target), "current")
})

test_that("restores never write into .git or gptr's user directories; control paths ask", {
  proj = local_project()
  g = ckpt_restore_guard(file.path(proj, ".git", "config"))
  expect_false(g$ok)
  expect_match(g$reason, ".git")
  u = ckpt_restore_guard(path_norm(file.path(gptr_user_dir("config"), "settings.json")))
  expect_false(u$ok)
  expect_match(u$reason, "user directory")
  ok = ckpt_restore_guard(file.path(proj, "R", "a.R"))
  expect_true(ok$ok)
  expect_false(ok$ask)
  ctl = ckpt_restore_guard(file.path(proj, ".gptr", "settings.json"))
  expect_true(ctl$ok)
  expect_true(ctl$ask)
})

test_that("slow walks switch the session to one scan per turn plus predicted paths", {
  local_gptr_options(checkpoint_scan_budget = -1, checkpoint_capture_max = 20)
  proj = local_project(files = list("R/a.R" = "a = 1"))
  ck = ckpt_ck_new("s0000000027")
  call = list(id = "c1", name = "r", input = list(code = "writeLines('a = 2', 'R/a.R')"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("a = 2", file.path(proj, "R", "a.R"))
  frag = ckpt_files_after(ck, call, tok)
  expect_identical(names(paths_status(frag)), "R/a.R")
  expect_true(ck$files$per_turn)
  call2 = list(id = "c2", name = "write", input = list(path = "R/b.R", content = "b = 1"))
  tok2 = ckpt_files_before(ck, call2, turn = 1L)
  writeLines("b = 1", file.path(proj, "R", "b.R"))
  writeLines("unpredicted", file.path(proj, "other.txt"))
  frag2 = ckpt_files_after(ck, call2, tok2)
  expect_length(frag2$files, 1L)
  expect_true(frag2$files[[1L]]$abs)
  expect_identical(basename(frag2$files[[1L]]$path), "b.R")
  turn_frag = ckpt_files_turn_scan(ck, 1L)
  expect_identical(names(paths_status(turn_frag)), "other.txt")
  call3 = list(id = "c3", name = "write", input = list(path = "R/a.R", content = "big"))
  tok3 = ckpt_files_before(ck, call3, turn = 2L)
  writeLines(strrep("y", 100), file.path(proj, "R", "a.R"))
  frag3 = ckpt_files_after(ck, call3, tok3)
  expect_identical(frag3$files[[1L]]$status, "modified")
  expect_null(ckpt_files_turn_scan(ck, 2L))
  expect_true(ckpt_files_undo(ck, frag3)$ok)
  expect_identical(readLines(file.path(proj, "R", "a.R")), "a = 2")
  # a predicted path that unpredicted code changed earlier in the turn is left to the turn scan
  call4 = list(id = "c4", name = "r", input = list(code = "source('job.R')"))
  tok4 = ckpt_files_before(ck, call4, turn = 3L)
  writeLines("job output", file.path(proj, "R", "a.R"))
  expect_null(ckpt_files_after(ck, call4, tok4))
  call5 = list(id = "c5", name = "write", input = list(path = "R/a.R", content = "c5"))
  tok5 = ckpt_files_before(ck, call5, turn = 3L)
  writeLines("c5", file.path(proj, "R", "a.R"))
  expect_null(ckpt_files_after(ck, call5, tok5))
  expect_true(ckpt_files_undo(ck, ckpt_files_turn_scan(ck, 3L))$ok)
  expect_identical(readLines(file.path(proj, "R", "a.R")), "a = 2")
})

test_that("files that cannot be read are listed, never captured and stop nothing else", {
  skip_on_os("windows")
  proj = local_project(files = list("R/a.R" = "a = 1", "R/b.R" = "b = 1", "secret.txt" = "s"))
  Sys.chmod(file.path(proj, "secret.txt"), "0000", use_umask = FALSE)
  skip_if(file.access(file.path(proj, "secret.txt"), 4L) == 0L, "the file stays readable")
  ck = ckpt_ck_new("s0000000030")
  call = list(id = "c1", name = "write", input = list(path = "secret.txt", content = "t"))
  tok = ckpt_files_before(ck, call, turn = 1L)
  writeLines("a = 2", file.path(proj, "R", "a.R"))
  Sys.chmod(file.path(proj, "R", "b.R"), "0000", use_umask = FALSE)
  Sys.chmod(file.path(proj, "secret.txt"), "0600", use_umask = FALSE)
  writeLines("k", file.path(proj, "key.pem"))
  Sys.chmod(file.path(proj, "key.pem"), "0000", use_umask = FALSE)
  frag = ckpt_files_after(ck, call, tok)
  expect_identical(paths_status(frag), c(key.pem = "created", `R/a.R` = "modified"))
  expect_true(all(ckpt_files_undo(ck, frag)$ok))
  expect_identical(readLines(file.path(proj, "R", "a.R")), "a = 1")
  expect_false(file.exists(file.path(proj, "key.pem")))
  expect_identical(readLines(file.path(proj, "secret.txt")), "s")
})

test_that("a forced turn scan records what a CLI child changed (IC-65)", {
  proj = local_project(files = list("R/a.R" = "a = 1"))
  ck = ckpt_ck_new("s0000000028")
  ckpt_files_sync(ckpt_files_tr(ck))
  expect_null(ckpt_files_turn_scan(ck, 1L, force = TRUE))
  writeLines("a = 2", file.path(proj, "R", "a.R"))
  frag = ckpt_files_turn_scan(ck, 1L, force = TRUE)
  expect_identical(paths_status(frag), c(`R/a.R` = "modified"))
  u = ckpt_files_undo(ck, frag)
  expect_true(u$ok)
  expect_identical(readLines(file.path(proj, "R", "a.R")), "a = 1")
})
